[package]
name = "rantt"
description = "A project planning app"
version = "0.1.0"
authors = ["sleb <scott.g.lebaron@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
dirs = "3"
serde = { version = "1", features = ["derive"]}
serde_json = "1.0"
toml = "0.5"